# Site settings
title: Patalyze
email: your-email@domain.com
exclude: [ "s3_website.yml" ]
description: "Patalyze is an experimental project exploring publicly available patent data."
baseurl: ""
url: "http://www.patalyze.co"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
permalink: pretty
